import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.scss'
import LeftBar from '../components/home/leftBar'
import { Navbar, Text } from "@nextui-org/react";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LeftBar />
        <Navbar isBordered variant="sticky">
          <Navbar.Brand>
            <Text b color="inherit" hideIn="xs">
              ACME
            </Text>
          </Navbar.Brand>
        </Navbar>
      </main>
    </div>
  )
}

export default Home
